### ISSUE TITLE
The folder is empty - examples/http-multi-backend/

### ISSUE THREAD

**Issue by ttsrg** [gruntwork-io/terraform-google-load-balancer#10]
Hello.
I beg my pardon, but subj.
terraform-google-load-balancer/examples/http-multi-backend/

**Comment by yorinasub17** [comment]
Hi @ttsrg , this is understandably confusing, but the docs refer to the code at the root of the repo as mentioned in the README. We have it this way because the terraform registry requires an example at the root of the repo, so we use the core example as the root.
