### ISSUE TITLE
Missing HTTP load balancing example

### ISSUE THREAD

**Issue by giefferre** [gruntwork-io/terraform-google-load-balancer#18]
As far as today the repository is missing a full, clear example of how to use the module to create HTTP multi backend load balancers.

The [examples/http-multi-backend](https://github.com/gruntwork-io/terraform-google-load-balancer/tree/21ff891d4529155ef4d37eb6d8c9141f29ffacc1/examples/http-multi-backend) only contains a README :(

Is it an intentional choice? Am I missing something?

Thanks in advance for your kind help

**Comment by MoonMoon1919** [comment]
As per the message above, we will be closing this issue.
