### ISSUE TITLE
How to provide credentials

### ISSUE THREAD

**Issue by maluyvova** [gruntwork-io/terraform-google-load-balancer#19]
Error:
Attempted to load application default credentials since neither `credentials` nor `access_token` was set in the provider block.  No credentials loaded. To use your gcloud credentials, run 'gcloud auth application-default login'.  Original error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

Official google provider has it

provider "google" {
  project     = var.project_id
  version     = "~> 3.43.0"
  credentials = file(var.gcp_auth_file)
  region      = "us-central1"
}

But in module (Lad balancer I can't find it)

module "load-balancer" {
  source  = "gruntwork-io/load-balancer/google"
  version = "0.3.0"
  region      = "us-central1"
  project     = var.project_id
  zone = "us-west1-a"
}

**Comment by Etiene** [comment]
Apologies for the delay in responding to this PR. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io

**Comment by MoonMoon1919** [comment]
As per the message above, we will be closing this issue.
