### ISSUE TITLE
Feature request: Internal Loadbalancer's healthcheck path and other options

### ISSUE THREAD

**Issue by charims** [gruntwork-io/terraform-google-load-balancer#23]
There seems to be some missing options on the internal loadbalancer health checks. For the http healthcheck, there is no path option, so it only supports "/" right now. As well, thresholds, intervals, and timeouts are currently not configuraable for http and tcp health checks.

**Comment by Etiene** [comment]
Apologies for the delay in responding to this issue. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io

**Comment by MoonMoon1919** [comment]
As per the message above, we will be closing this issue.
