### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/terraform-google-load-balancer#26]
The tests are failing on the `update gcloud` stage. Screenshot below & [link here](https://app.circleci.com/pipelines/github/gruntwork-io/terraform-google-load-balancer/76/workflows/a97bace5-6377-4b20-b8e8-2e03dd24a432/jobs/120):

<img width="1099" alt="Screenshot 2021-07-13 at 18 45 59" src="https://user-images.githubusercontent.com/32835571/125483289-9297e776-59c7-48e6-ac7c-afc094289e71.png">

**Comment by MoonMoon1919** [comment]
Closing this as it appears to have been fixed.
